# Generated by Django 5.1.4 on 2025-01-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_alter_headers_email_alter_headers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
