# Generated by Django 5.1.4 on 2025-01-14 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_alter_headers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('user', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('job_description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
