# Generated by Django 5.1.4 on 2025-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_professionalexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
