# Generated by Django 5.1.4 on 2025-01-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_education_hobbies_languages_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
    ]
