# Generated by Django 5.1.4 on 2025-01-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_alter_education_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalexperience',
            name='company',
        ),
        migrations.RemoveField(
            model_name='professionalexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='professionalexperience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='professionalexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='company1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='company2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='company3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='company4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='end_date1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='end_date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='end_date3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='end_date4',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='job_description2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='job_description3',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='job_description4',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='location1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='location2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='location3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='location4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='start_date1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='start_date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='start_date3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='start_date4',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='job_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
