# Generated by Django 5.1.4 on 2025-01-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_remove_professionalexperience_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalexperience',
            old_name='job_description',
            new_name='job_description1',
        ),
    ]
