# Generated by Django 5.1.4 on 2025-01-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0010_rename_job_description_professionalexperience_job_description1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='company1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='company2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='company3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='company4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='job_description1',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='job_description2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='job_description3',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='job_description4',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='location1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='location2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='location3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='location4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
