# Generated by Django 5.1.4 on 2025-01-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_alter_professionalexperience_company1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='end_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='end_date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='end_date3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='end_date4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='start_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='start_date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='start_date3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='start_date4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
