# Generated by Django 5.1.4 on 2025-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0014_alter_education_cgpa1_alter_education_degree1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='basic_intro',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
