# Generated by Django 5.1.4 on 2025-01-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0015_headers_basic_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headers',
            name='basic_intro',
        ),
    ]
