# Generated by Django 5.1.4 on 2025-01-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0018_alter_education_user_alter_headers_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalexperience',
            name='end_date1',
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='designation1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='designation2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='designation3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='designation4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
