# Generated by Django 5.1.4 on 2025-01-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0019_remove_professionalexperience_end_date1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_date1',
            new_name='ended_date1',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='end_date2',
            new_name='ended_date2',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='end_date3',
            new_name='ended_date3',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_date1',
            new_name='started_date1',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_date2',
            new_name='started_date2',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_date3',
            new_name='started_date3',
        ),
    ]
