# Generated by Django 5.1.4 on 2025-01-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0020_rename_end_date1_education_ended_date1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='location2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='location3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
