# Generated by Django 5.1.4 on 2025-01-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0021_education_location1_education_location2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='location1',
            new_name='locationed1',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='location2',
            new_name='locationed2',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='location3',
            new_name='locationed3',
        ),
    ]
